### ISSUE TITLE
Dockerize React app

### ISSUE THREAD

**Issue by naXa777** [this-mkhy/react-curve#13]
Let's add Dockerfile, .dockerignore, and docker-compose.yml to your project.
More information in the article -> https://www.knowledgehut.com/blog/web-development/how-to-dockerize-react-app
I'm going to follow it step by step. Please assign me to this task.

Read here to learn more about what is Docker and why it's used https://www.docker.com/why-docker/

**Comment by this-mkhy** [comment]
Great, You can start @naXa777

**Comment by naXa777** [comment]
@this-mkhy, I've delegated this task to a fellow junior developer as part of programming training. She completed this task today. Please merge PR #36 ASAP. Thank you!
